name: Swift

on: [push]

jobs:
  build:
    strategy:
      matrix:
        swift: ["5.8"]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Internxt Swift Core
        run: swift build
      - name: Run tests
        run: swift test
