name: Internxt Swift Core Unit Tests

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5"
      - uses: actions/checkout@v3
      - name: Build Internxt Swift Core
        run: swift build
      - name: Run tests
        run: swift test
